site_name: chartlets

nav:
  - Home: index.md
  - Demo: demo.md
  - Usage: usage.md
  - Components: components.md
  - About: about.md

theme:
  name: material
  locale: en
  #include_sidebar: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  toggle:
    icon: material/brightness-4
    name: Switch to light mode

repo_url: https://github.com/bcdev/chartlets

site_description: Documentation of the chartlet software framework
copyright: Brockmann Consult GmbH

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
