name: dashi
channels:
  - conda-forge
dependencies:
  - python
  # Dependencies
  - pandas
  - plotly
  - pyaml
  - tornado
  # Dev Dependencies
  - black
  - flake8
  - pytest
  - pytest-cov
  - requests-mock
