name: chartlets
channels:
  - conda-forge
dependencies:
  # Library Dependencies
  - python >=3.12,<3.13
  - altair
  # Demo Dependencies
  - pandas
  - pyaml
  - tornado
  # Dev Dependencies
  - black
  - flake8
  - pytest
  - pytest-cov
  - requests-mock
