name: dashi
channels:
  - conda-forge
dependencies:
  - python >=3.12,<3.13
  # Dependencies
  - pandas
  - altair
  - pyaml
  - tornado
  # Dev Dependencies
  - black
  - flake8
  - pytest
  - pytest-cov
  - requests-mock
