name: Chartlets CI workflow
on: [push]

jobs:
  backend_chartlets-py:
      runs-on: ubuntu-latest
      steps:
        - name: git-checkout chartlets
          uses: actions/checkout@v4
        - name: Set up Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            environment-file: chartlets.py/environment.yml
        - name: Run unit tests
          shell: bash -l {0}
          run: |
            cd chartlets.py 
            pytest
