name: Package and Publish

on:
  release:
    types: [published]

jobs:
  PyPi-Deploy:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to PyPI
      run: |
        pip install twine
        python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*

  npm-Deploy:
    name: Publish TS-React Package to npmjs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci  
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
